### PR TITLE
Prefer X headers for verify param and port

### PR DESCRIPTION
**Pull request by Subreptivus**
* Due to the limitations of Envoy config we cannot set `x-eas-verify-params` header on listener's level for GRPC approach. So we decided to do it with Lua filter before `ext_authz` filter.
* We're trying to run Envoy with least amount of privileges, hence we aren't using "high" ports like `443`, I think it's currently the default Istio installation. So our Envoy HTTPS listener is on port `8443`, but for ingress traffic it's `443`. But when the request is made from reply uri the port will be `8443` as it is constructed from `request.attributes.destination.address.socket_address` in `x-eas-request-uri`.

In both cases the preference should go to `x-eas-verify-params` or `x-forwarded-port` headers if they are present in request for GRPC server.

### CODE REVIEW

**Comment by travisghansen** [comment]
I’ll look at this a bit more closely in the next couple days with more feedback. As I recall the context metadata could be set on a per vhost basis…the configuration generally seemed a little odd to me though. I’m far from an envoy expert however.

A primary concern/consideration here is the ability to trust/sanitize the headers that are passed into the filter. Unlike the http style integration the grpc didn’t allow for the same kind of control. This was originally why I went with context data vs headers to have a more ‘secure by default’ posture. Again with limited envoy experience I could be misunderstanding things for sure though and would love input!

**Comment by travisghansen** [comment]
Thanks for your patience getting back to this.  Can the lua filters set context values instead of actual headers?

I have (as stated before) concerns about how the headers are managed (or not) in the grpc scenario. The context can be trusted as external actors cannot even possibly directly manipulate the context data making far more secure. My thought is to look at similar named context params (instead of headers) for reading the port etc

**Comment by Subreptivus** [comment]
No, it can't (context values can't be altered dynamically AFAIK).
On the other hand, it can manage `metadata`, like the following snippet from docs:
````
function envoy_on_request(request_handle)
    local headers = request_handle:headers()
    request_handle:streamInfo():dynamicMetadata():set("envoy.lua", "request.info", {
      auth: headers:get("authorization),
      token: headers:get("x-request-token"),
    })
end
````

**Comment by travisghansen** [comment]
Can test if the metadata is in the grpc request somewhere?

**Comment by Subreptivus** [comment]
Yes I can

**Comment by travisghansen** [comment]
OK, I have this prototyped out. It requires 2 things:

1. adding in the filter before the authz filter is invoked
2. ensure the authz config contains the proper value for `metadata_context_namespaces`

```
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local headers = request_handle:headers()
                  request_handle:streamInfo():dynamicMetadata():set("blah", "fooabr", {
                    foo = "bar",
                    bar = "baz",
                  })
                end
... 
         - name: envoy.filters.http.ext_authz-grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              stat_prefix: ext_authz_eas
              transport_api_version: V3
              metadata_context_namespaces:
              - envoy.filters.http.lua
              - blah
...
```

Results in the `grpc` call data including..

```
{
...
         "metadata_context":{
            "filter_metadata":{
               "blah":{
                  "fields":{
                     "fooabr":{
                        "structValue":{
                           "fields":{
                              "bar":{
                                 "stringValue":"baz",
                                 "kind":"stringValue"
                              },
                              "foo":{
                                 "stringValue":"bar",
                                 "kind":"stringValue"
                              }
                           }
                        },
                        "kind":"structValue"
                     }
                  }
               }
            }
         }
      }
   }
}
```

**but** all of this may be unnecessary, can you set the `initial_metadata` value on the authz filter with the granularity required for your use-case? If so the token and port etc could be added there.

```
          - name: envoy.filters.http.ext_authz-grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              stat_prefix: ext_authz_eas
              transport_api_version: V3
              metadata_context_namespaces:
              - envoy.filters.http.lua
              - blah
              filter_enabled:
                default_value:
                  # 0 effectively disables the filter
                  numerator: 100
                  denominator: HUNDRED
              grpc_service:
                initial_metadata:
                - key: foobar
                  value: baz
                envoy_grpc:
                  cluster_name: eas-grpc
                timeout: 5.00s

```

**Comment by travisghansen** [comment]
OK, this is implemented in the `next` branch/images. There is a fall through list of preference for each of the following:

- verify params
- proto
- port

For each the preference is in the following order:

1. header (only for proto since it can generally be trusted)
2. filter metadata (see below)
3. initial metadata (see below)
4. context
5. implicit data (such as the port envoy is running on etc)

## filter metadata syntax

```
          http_filters:
          - name: envoy.filters.http.lua
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  local headers = request_handle:headers()
                  request_handle:streamInfo():dynamicMetadata():set("eas", "eas", {
                    -- must use this key syntax due to hyphens in key name
                    -- must add `eas` to `metadata_context_namespaces` in the authz filter
                    -- remove the `--` below for the values/lines you wish to explicitly set/override
                    -- ["x-eas-verify-params"] = '{"config_token_store_id":"dep_a", "config_token_id":"keycloak"}',
                    -- ["x-forwarded-port"] = 443,
                    -- ["x-forwarded-proto"] = "http",
                  })
                end
...
          - name: envoy.filters.http.ext_authz-grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              metadata_context_namespaces:
              - eas
```

## initial metadata syntax

```
          - name: envoy.filters.http.ext_authz-grpc
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
              stat_prefix: ext_authz_eas
              transport_api_version: V3
              grpc_service:
                # uncomment the fields below you wish to explicitly set/override
                initial_metadata:
                #- key: x-eas-verify-params
                #  value: '{"config_token_store_id":"dep_a", "config_token_id":"keycloak"}'
                #- key: x-forwarded-proto
                #  value: https
                #- key: x-forwarded-port
                #  value: 443
                envoy_grpc:
                  cluster_name: eas-grpc
                timeout: 5.00s
```

Give it a try and let me know how it goes.

Side note, I've updated the deps/images to use node 16 instead of 12.

**Comment by travisghansen** [comment]
Did you get a chance to try the new code out?

**Comment by Subreptivus** [comment]
Hi!
I beg your pardon for such huge delay. I'm not using Istio anymore (or for now), but I'm really admire this project and wanted to help it still. Hence I had to replicate my previous environment from scratch.
Anyhow, I did try it out, and it's working as expected! I was testing only p. 2 and 3, yet other should work as expected I guess...
I'm really appreciate your support and critical thinking, now it's much better covered than in this PR, so I'm going to close it.

**Comment by travisghansen** [comment]
Great!

**Pull request closed without merging**
