### PR TITLE
add podLabels parameter

### PR DESCRIPTION
**Pull request by t3mi**
Adds configuration of additional pod labels, like cost center.

### CODE REVIEW

**Comment by travisghansen** [comment]
Do you think we should pump the value through the `tpl` function to allow for dynamic content?

**Comment by t3mi** [comment]
I doubt that as this is only needed for pods. `tpl` functions are useful if you want to apply some common labels for all resources not limiting to podSpec.

**Comment by travisghansen** [comment]
Sure, I mean something like this (example from another project):

```
  {{- range .Values.controller.externalAttacher.args }}
  - {{ tpl . $root }}
  {{- end }}
```

That would allow (in this context) to do something like this:

```
arbitraryStuff:
  something: otherthing
podLabels:
  foo: bar-{{ .Release.Namespace }}
  bar: baz-{{ .Release.Namespace }}-{{ .Values.arbitraryStuff.something }}
```

**Comment by t3mi** [comment]
Sorry, I misunderstood you. Switched to use of `tpl` function.

**Comment by travisghansen** [comment]
Thanks for the contribution!

**Pull request merged**
