### PR TITLE
Example Keycloak OIDC Generator

### PR DESCRIPTION
**Pull request by autarchprinceps**
We have created another script to generate a configuration for Keycloak OpenID Connect configuration. It is redirecting to Keycloak correctly, but when it returns to the page after the login, it returns with a 5xx. Looking into the External Auth Server logs, it throws the following exception:
```
{
"level":"error",
"service":"external-auth-server",
"message":"Cannot read property 'data' of undefined",
"stack":"TypeError: Cannot read property 'data' of undefined\n at OpenIdConnectPlugin.prepare_token_headers (/home/eas/app/src/plugin/oauth/index.js:775:30)\n at OpenIdConnectPlugin.verify (/home/eas/app/src/plugin/oauth/index.js:660:24)\n at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```

Looking at the code, it seems to have an undefined in the sessionData.userinfo field of the prepare_token_headers. I have tried to follow the example under https://github.com/travisghansen/external-auth-server/blob/master/PLUGINS.md#oidc 
I didn't impose any additional restrictions, like in the github teams example, and if I look at the code for getting custom userinfo, it seems to only support GitHub as a source anyway. Your Readme says, you mainly tested with Keycloak, so I assume this can be made to work, but I don't know what I did wrong.

### CODE REVIEW

**Comment by travisghansen** [comment]
I'm guessing you're on a little earlier version, and for some reason userinfo did not get fetched.

If you update the error will probably go away but you'll likely fail any userinfo assertions should you have them.

Can you send over what you have for a `config_token`? Stripping sensitive stuff is fine.

**Comment by travisghansen** [comment]
Sorry, originally viewed this on my phone, I see in your config generator you have `fetch_userinfo: false` which combined with the older version of `eas` is resulting in the failure. I fixed the issue a little while back but I'm guessing you want that turned on regardless. Update to latest and/or turn that on and I'm fairly confident your issues will go away.

**Comment by travisghansen** [comment]
To shed some additional light on the `userinfo` situation, `oidc` implicitly supports `userinfo` as it's part of the spec, however `oauth` has no such notion built-in. Many `oauth` providers however implement various calls that can be invoked to retrieve the equivalent of `userinfo` in provider specific manners. Currently the only supported provider for `oauth` in `eas` is github, but others could be added pretty easily.

**Comment by autarchprinceps** [comment]
You are correct, with fetch_userinfo: true and version 0.6 of the image, it now works fundamentally (meaning without assertions, as currently committed here). You said with OpenID Connect userinfo is part of the spec. Do you have some reference or knowledge of how the userinfo data is formatted then / what it contains? I understand the fundamentals of how to write assertions, I mean in terms of what data is provided that I could query against. I would probably add the option to limit it to a group of a realm in keycloak, similar to how we could limit it to teams, etc. in GitHub. That would probably be the most helpful as an example for other users as well, perhaps with the note, that this could be removed to just allow every logged in member of a realm access.

**Comment by travisghansen** [comment]
I'll have to dig through my notes. I don't believe the spec calls out the structure of the content (other than json I guess, but specific fields etc no). That will probably differ from provider to provider. Also note that since oidc forces the token to be a jwt you will often find group membership in the token itself vs userinfo. If I recall correctly that was the case with keycloak.

In either case you can run assertions against the data which is good. As I move to 1.0 release I'm actually going to make assertion logic/configuration more generic and simultaneously change the scope of the dataset being asserted to include all of the data (token, userinfo, request, config). Doing so retains the existing power but adds the ability to assert across datasets (ie: token.email = userinfo.email...or req.host.split(".")[0] is in token.groups).

I'll dig into the keycloak output I have to see where groups land and shoot it over.

**Comment by travisghansen** [comment]
Ok, I did some research and got an answer for you. Long story short, it's all configurable in keycloak but not enabled by default. In my case, I did a 2 step process but you may skip the first:

1. Since I'm using ldap user federation, I went into the ldap provider configuration and setup the group mapper (this was pretty simple generally) and set up keycloak to sync group membership from ldap. You of course can skip this if you're managing groups solely in keycloak.

1. This is the important one, add the group mapper to your client. Clients -> pick your client -> mappers. Click create and in the form select "Group Membership" for the mapper type. Whatever you put in the "Token Claim Name" field is what the attribute will be called in the various datasets. After that you can pick to include the data into any/all of the tokens (id_token, access_token, userinfo).

I'm not a keycloak guru so I'm sure there are probably a hundred ways to solve this, but that's a simple example.

**Comment by travisghansen** [comment]
Were you able to sort out groups?

**Comment by travisghansen** [comment]
Any luck with the group stuff?

**Pull request merged**
