### PR TITLE
fix: adds missed cache_ttl to cache set function

### PR DESCRIPTION
**Pull request by ryanandonian**
Fixes https://github.com/travisghansen/external-auth-server/issues/155

### CODE REVIEW

**Comment by ryanandonian** [comment]
I used a final comma on the params, but I realized that potentially will not be consistent with your style, I can remove it if you want @travisghansen

**Comment by travisghansen** [comment]
I actually did notice this a couple weeks ago when I looked at it but I don't think it will fix the issue (and I have a patch queued up). This will simply make the purging more aggressive but in theory this check should fail:

```
    let publicKeys;

    publicKeys = await store.get(FIREBASE_JWT_KEYS_CACHE_KEY);

    if (publicKeys == null) {
...
```

Here's my current diff (excuse the silly syntax updates):

```
diff --git a/src/plugin/firebase/index.js b/src/plugin/firebase/index.js
index 7b91376..550ac01 100644
--- a/src/plugin/firebase/index.js
+++ b/src/plugin/firebase/index.js
@@ -58,7 +58,7 @@ class FirebaseJwtPlugin extends BasePlugin {
     scheme = scheme.toLowerCase();
 
     let error, error_description;
-    const failure_response = function(code = 401) {
+    const failure_response = function (code = 401) {
       res.statusCode = code || 401;
 
       if (scheme == "bearer") {
@@ -115,9 +115,9 @@ class FirebaseJwtPlugin extends BasePlugin {
       publicKeys = await new Promise((resolve, reject) => {
         const options = {
           method: "GET",
-          url: FIREBASE_JWT_KEYS_URI
+          url: FIREBASE_JWT_KEYS_URI,
         };
-        request(options, function(error, res, body) {
+        request(options, function (error, res, body) {
           if (error) {
             reject(error);
           }
@@ -125,7 +125,7 @@ class FirebaseJwtPlugin extends BasePlugin {
           if (res.headers.hasOwnProperty("cache-control")) {
             const cacheControlHeader = res.headers["cache-control"];
             const parts = cacheControlHeader.split(",");
-            parts.forEach(part => {
+            parts.forEach((part) => {
               const subParts = part.trim().split("=");
               if (subParts[0] === "max-age") {
                 const maxAge = +subParts[1];
@@ -138,11 +138,13 @@ class FirebaseJwtPlugin extends BasePlugin {
       });
 
       if (cache_ttl) {
-        await store.set(FIREBASE_JWT_KEYS_CACHE_KEY, publicKeys);
+        await store.set(FIREBASE_JWT_KEYS_CACHE_KEY, publicKeys, cache_ttl);
       }
     } else {
       plugin.server.logger.verbose(
-        "firebase-jwt: using cached public signing keys"
+        `firebase-jwt: using cached public signing keys: ${JSON.stringify(
+          publicKeys
+        )}`
       );
     }
 
@@ -156,6 +158,11 @@ class FirebaseJwtPlugin extends BasePlugin {
     config.options.audience = config.project_id;
 
     function getKey(header, callback) {
+      plugin.server.logger.verbose(
+        `firebase-jwt: looking for kid: ${header.kid}, publicKeys: ${JSON.stringify(
+          publicKeys
+        )}`
+      );
       const key = publicKeys[header.kid];
       callback(null, key);
     }
@@ -211,7 +218,7 @@ class FirebaseJwtPlugin extends BasePlugin {
 
         res.setAuthenticationData({
           id_token: creds.token,
-          userinfo: userinfo
+          userinfo: userinfo,
         });
         res.statusCode = 200;
         return res;
@@ -251,14 +258,14 @@ class FirebaseJwtPlugin extends BasePlugin {
           method: "POST",
           url: FIREBASE_USERINFO_URI + "?key=" + plugin.config.config.api_key,
           headers: {
-            "Content-Type": "application/json"
+            "Content-Type": "application/json",
           },
           json: true,
           body: {
-            idToken: id_token
-          }
+            idToken: id_token,
+          },
         };
-        request(options, function(error, res, body) {
+        request(options, function (error, res, body) {
           if (error) {
             reject(error);
           }
@@ -278,7 +285,7 @@ class FirebaseJwtPlugin extends BasePlugin {
 
       plugin.server.logger.verbose("userdata: %j", userdata);
 
-      userinfo = userdata.users.find(function(element) {
+      userinfo = userdata.users.find(function (element) {
         return element.localId == decoded_id_token.sub;
       });
 
@@ -332,5 +339,5 @@ class FirebaseJwtPlugin extends BasePlugin {
 }
 
 module.exports = {
-  FirebaseJwtPlugin
+  FirebaseJwtPlugin,
 };
```

**Comment by ryanandonian** [comment]
It looks like the cache defaults to `ttl = 0`, so wouldn't leveraging the `max-age` be a proper solution? Looks like your diff has that line as well.

https://github.com/travisghansen/external-auth-server/blob/master/src/store.js#L46
```javascript
function set(key, val, ttl = 0) {
```

The issue here seems like we're caching something with an indefinite lifetime, so after the first request, this `get` call will never return a falsy response, since the key will never expire or be evicted (note: our cache key set is light, so it will never get evicted by sheer volume or max size)

```javascript
publicKeys = await store.get(FIREBASE_JWT_KEYS_CACHE_KEY);
```

**Comment by travisghansen** [comment]
> It looks like the cache defaults to `ttl = 0`, so wouldn't leveraging the `max-age` be a proper solution? Looks like your diff has that line as well.
> 
> https://github.com/travisghansen/external-auth-server/blob/master/src/store.js#L46
> 
> ```js
> function set(key, val, ttl = 0) {
> ```
> 
> The issue here seems like we're caching something with an indefinite lifetime, so after the first request, this `get` call will never return a falsy response, since the key will never expire or be evicted (note: our cache key set is light, so it will never get evicted by sheer volume or max size)
> 
> ```js
> publicKeys = await store.get(FIREBASE_JWT_KEYS_CACHE_KEY);
> ```

You are correct, I think the patch (yours or mine) will resolve the issue. I didn't realize they cycled those issuing keys so quickly so that was a bad assumption on my part driving that comment.

Thanks for the patience and fix!

**Comment by ryanandonian** [comment]
> Thanks for the patience and fix!

No worries! Thanks for maintaining this and being so responsive :) 

If you want to merge this PR, that would have a smaller `diff` and might make it easier down the line to `blame` heh.

**Comment by ryanandonian** [comment]
Closing this one as #157 includes this cache fix patch 🎉

**Pull request closed without merging**
