### PR TITLE
Upgrade redis to a new version and disable affinity by default

### PR DESCRIPTION
**Pull request by mlushpenko**
We'd like to run the whole setup on a single node on dev/test environments and newer version of chart supports disabling hard anti affinity.

It's a better solution than overriding a full description which would be required in an older version:
```
affinity: |
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: {{ template "redis-ha.name" . }}
            release: {{ .Release.Name }}
        topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app:  {{ template "redis-ha.name" . }}
              release: {{ .Release.Name }}
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

### CODE REVIEW

**Comment by travisghansen** [comment]
I like this minus the default. I think we should leave it at `true`.

**Comment by mlushpenko** [comment]
Updated, make sense, I did it with our use-case in mind in the beginning.

**Comment by mlushpenko** [comment]
@travisghansen could you please release 0.8.1 with this change? we'd like to move back to the original repo and 0.8.0 tag reverts Redis to version 3.5.0

**Comment by travisghansen** [comment]
Yes, I will in approximately an hour.

**Comment by mlushpenko** [comment]
Thanks a lot

**Comment by travisghansen** [comment]
Actually this is just a change to the chart..it should already be available in the helm repo.  Since we didn't bump the version you may need to force an update of the repo and/or clear the helm cache.

Regardless, I'll be snapping a new release today.

**Comment by mlushpenko** [comment]
We use the following "management" file for helm charts:
```
apiVersion: dimension/v1
kind: HelmChart
metadata:
  name: eas
name: external-auth-server
namespace: "auth"
git_source:
  url: https://github.com/travisghansen/external-auth-server
  branch: v0.8.0
  path: charts/external-auth-server
values:
- ../../base/values.yml
- values.yml.secret
```

so, I can change branch to master, but we'd like to have a more controlled way to get updates, so tags are better.

**Comment by travisghansen** [comment]
Ah! I see. Let me see what I can do. I started a pretty large update bumping all the dependencies so I'll see where that lands.

**Pull request merged**
