### PR TITLE
Create a full config using env vars

### PR DESCRIPTION
**Pull request by runningman84**
In order to simplify the setup of multiple clusters, we have created a config generator which just needs a bunch of env variables.

### CODE REVIEW

**Comment by travisghansen** [comment]
Interesting, let me have a closer look and I'll comment again. Thanks for the help!

**Comment by travisghansen** [comment]
This is great! I think I'd like to change the structure slightly though. Let's introduce a `contrib` directory to house these kinds of examples. Also, let's me more explicit in the naming of the file to include:

- helm
- traefik
- github

It's pretty specific to those 3 things so we'll just make it a bit more clear to others not coming from those environments. I'm ok adding the yaml dep. Sound good?

**Comment by runningman84** [comment]
That's fine for me

**Comment by runningman84** [comment]
I have moved the stuff to the contrib directory. Can you merge it now?

**Comment by travisghansen** [comment]
Thanks for the contribution!

**Pull request merged**
